name: my_app_one
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  http: ^1.2.0
  intl: ^0.17.0
  flutter_dotenv: ^5.0.2
  uuid: ^4.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  

  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/animations/splash_animation.json
